const canvas = document.getElementById("snake-canvas"), ctx = canvas.getContext("2d");
const box = 20, grid = canvas.width / box;
const $ = id => document.getElementById(id);
const scoreEl = $("score"), bestEl = $("best-score"), statusEl = $("game-status"), powerEl = $("power-status");
const difficultyEl = $("difficulty"), skinEl = $("skin"), mapEl = $("map"), obstaclesEl = $("obstacles"), dailyEl = $("daily"), vibrationEl = $("vibration"), nameEl = $("player-name");
const speedBase = { easy: 155, medium: 112, hard: 78 };
let snake = [], food, rocks = [], particles = [], direction = "RIGHT", nextDirection = "RIGHT", score = 0, timer, started = false, paused = false, counting = false, wallWraps = 0;
let power = { shield: 0, magnet: 0, double: 0, ghost: 0 }, slowUntil = 0, audioContext, musicTimer, soundOn = true, musicOn = false;
let best = Number(localStorage.getItem("snakeArenaBest") || 0), leaderboard = JSON.parse(localStorage.getItem("snakeArenaLeaderboard") || "[]"), achievements = JSON.parse(localStorage.getItem("snakeArenaAchievements") || "{}"), stats = JSON.parse(localStorage.getItem("snakeArenaStats") || '{"games":0,"total":0,"longest":0,"daily":0}');
let seed = 1, dailyMode = false;

function seededRandom() { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; }
function rand() { return dailyMode ? seededRandom() : Math.random(); }
function randomCell() { return { x: Math.floor(rand() * grid), y: Math.floor(rand() * grid) }; }
function same(a, b) { return a.x === b.x && a.y === b.y; }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function cellOccupied(cell) { return snake.some(p => same(p, cell)) || rocks.some(p => same(p, cell)); }

function drawRound(x, y, w, h, r) { ctx.beginPath(); if (ctx.roundRect) ctx.roundRect(x, y, w, h, r); else ctx.rect(x, y, w, h); ctx.fill(); }
function renderLeaderboard() { const list = $("leaderboard"); list.innerHTML = ""; (leaderboard.length ? leaderboard : [{ name: "No scores yet", score: "-" }]).forEach(entry => { const li = document.createElement("li"), name = document.createElement("span"), points = document.createElement("strong"); name.textContent = entry.name; points.textContent = entry.score; li.append(name, points); list.appendChild(li); }); }
function unlock(id, label) { if (!achievements[id]) { achievements[id] = label; save("snakeArenaAchievements", achievements); renderAchievements(); statusEl.textContent = `Achievement unlocked: ${label}`; } }
function renderAchievements() { const list = $("achievement-list"); list.innerHTML = ""; const all = [{ id: "score100", name: "Century - score 100" }, { id: "rainbow", name: "Rainbow master" }, { id: "daily", name: "Daily challenger" }, { id: "survivor", name: "Long survivor" }]; all.forEach(item => { const li = document.createElement("li"); li.textContent = `${achievements[item.id] ? "Done" : "Locked"} - ${item.name}`; if (achievements[item.id]) li.className = "done"; list.appendChild(li); }); }
function renderStats() { $("stat-games").textContent = stats.games; $("stat-longest").textContent = stats.longest; $("stat-average").textContent = stats.games ? Math.round(stats.total / stats.games) : 0; $("stat-daily").textContent = stats.daily; }

function makeRocks() { rocks = []; if (!obstaclesEl.checked && !dailyMode) return; const count = dailyMode ? 8 : 6; while (rocks.length < count) { const cell = randomCell(), nearCenter = Math.abs(cell.x - grid / 2) < 5 && Math.abs(cell.y - grid / 2) < 5; if (!nearCenter && !rocks.some(r => same(r, cell))) rocks.push({ ...cell, dx: rand() < .5 ? -1 : 1, dy: rand() < .5 ? -1 : 1 }); } }
function placeFood() { let cell; do { cell = randomCell(); } while (cellOccupied(cell)); const roll = rand(), types = roll < .10 ? "bonus" : roll < .20 ? "slow" : roll < .27 ? "power" : "normal"; const powers = ["shield", "magnet", "double", "ghost"]; food = { ...cell, type: types, power: types === "power" ? powers[Math.floor(rand() * powers.length)] : null }; }
function speed() { let value = Math.max(40, speedBase[difficultyEl.value] - Math.floor(score / 50) * 5); if (Date.now() < slowUntil) value *= 1.55; return value; }
function configureTimer() { clearInterval(timer); if (started && !paused) timer = setInterval(tick, speed()); }
function dailySeed() { const now = new Date(); return Number(`${now.getFullYear()}${now.getMonth() + 1}${now.getDate()}`); }

function beginGame() { clearInterval(timer); dailyMode = dailyEl.checked; seed = dailyMode ? dailySeed() : Date.now() >>> 0; const mid = Math.floor(grid / 2); snake = [{ x: mid, y: mid }, { x: mid - 1, y: mid }, { x: mid - 2, y: mid }]; direction = nextDirection = "RIGHT"; score = wallWraps = 0; particles = []; power = { shield: 0, magnet: 0, double: 0, ghost: 0 }; slowUntil = 0; makeRocks(); placeFood(); started = true; paused = false; $("pause-btn").disabled = false; $("pause-btn").textContent = "Pause"; $("game-over-modal").hidden = true; $("start-modal").hidden = true; scoreEl.textContent = "0"; bestEl.textContent = best; $("daily-target").textContent = dailyMode ? "250" : "-"; powerEl.textContent = ""; statusEl.textContent = dailyMode ? "Daily target: 250. Rocks are active." : "Collect food and keep moving."; draw(); startCountdown(); }
function startCountdown() { counting = true; $("countdown-modal").hidden = false; let count = 3; $("countdown-number").textContent = count; const interval = setInterval(() => { count--; if (count <= 0) { clearInterval(interval); $("countdown-modal").hidden = true; counting = false; configureTimer(); statusEl.textContent = "Go!"; } else $("countdown-number").textContent = count; }, 750); }
function setDirection(value) { const opposite = { LEFT: "RIGHT", RIGHT: "LEFT", UP: "DOWN", DOWN: "UP" }; if (value !== opposite[direction]) nextDirection = value; }
function moveRocks() { if (!rocks.length || score < 50) return; rocks.forEach(rock => { const nx = rock.x + rock.dx, ny = rock.y + rock.dy; if (nx < 0 || nx >= grid) rock.dx *= -1; if (ny < 0 || ny >= grid) rock.dy *= -1; rock.x = (rock.x + rock.dx + grid) % grid; rock.y = (rock.y + rock.dy + grid) % grid; }); if (score >= 150 && rocks.length < 12) rocks.push({ ...randomCell(), dx: 1, dy: -1 }); }
function activePower(name) { return power[name] > Date.now(); }
function updatePowerStatus() { const names = Object.entries(power).filter(([, until]) => until > Date.now()).map(([name, until]) => `${name} ${Math.ceil((until - Date.now()) / 1000)}s`); powerEl.textContent = names.length ? `Power: ${names.join(" | ")}` : ""; }

function tick() { if (!started || paused || counting) return; if (slowUntil && Date.now() >= slowUntil) { slowUntil = 0; statusEl.textContent = "Slow motion ended."; configureTimer(); } direction = nextDirection; const head = { ...snake[0] }; if (direction === "LEFT") head.x--; if (direction === "RIGHT") head.x++; if (direction === "UP") head.y--; if (direction === "DOWN") head.y++;
  if (head.x < 0 || head.x >= grid || head.y < 0 || head.y >= grid) { wallWraps++; head.x = (head.x + grid) % grid; head.y = (head.y + grid) % grid; }
  moveRocks(); const willEat = same(head, food); const body = willEat ? snake : snake.slice(0, -1); const bodyHit = body.some(p => same(p, head)); const rockHit = rocks.some(p => same(p, head));
  if (bodyHit || (rockHit && !activePower("ghost"))) { if (activePower("shield")) { power.shield = 0; statusEl.textContent = "Shield saved you!"; vibrate(35); } else { endGame(); return; } }
  snake.unshift(head); if (willEat) eat(head); else snake.pop(); if (activePower("magnet") && Math.abs(head.x - food.x) + Math.abs(head.y - food.y) <= 2) eat(head); particles.forEach(p => { p.x += p.dx; p.y += p.dy; p.life--; }); particles = particles.filter(p => p.life > 0); updatePowerStatus(); draw(); }

function eat(head) { const points = { normal: 10, bonus: 30, slow: 15, power: 20 }; let gained = points[food.type] * (activePower("double") ? 2 : 1); score += gained; if (food.type === "slow") { slowUntil = Date.now() + 6000; statusEl.textContent = "Slow motion for 6 seconds."; configureTimer(); } else if (food.type === "power") { power[food.power] = Date.now() + 7000; statusEl.textContent = `${food.power.toUpperCase()} power-up active!`; } else statusEl.textContent = food.type === "bonus" ? `Bonus! +${gained}` : `+${gained} points`;
  for (let i = 0; i < 14; i++) particles.push({ x: head.x * box + box / 2, y: head.y * box + box / 2, dx: (Math.random() - .5) * 4, dy: (Math.random() - .5) * 4, life: 16, color: food.type === "power" ? "#c18cff" : food.type === "bonus" ? "#ffd166" : "#ff7777" }); sound(food.type); vibrate(15); scoreEl.textContent = score;
  if (score > best) { best = score; localStorage.setItem("snakeArenaBest", best); bestEl.classList.remove("best-pop"); void bestEl.offsetWidth; bestEl.classList.add("best-pop"); } bestEl.textContent = best; if (score >= 100) unlock("score100", "Century"); if (skinEl.value === "rainbow" && score >= 100) unlock("rainbow", "Rainbow master"); if (snake.length >= 25) unlock("survivor", "Long survivor"); if (dailyMode && score >= 250) { unlock("daily", "Daily challenger"); stats.daily = Math.max(stats.daily, score); save("snakeArenaStats", stats); renderStats(); } placeFood(); configureTimer(); }

function mapStyle() { return { cyber: ["#07131c", "rgba(132,255,214,.08)"], forest: ["#102313", "rgba(164,222,116,.11)"], space: ["#0b0b26", "rgba(152,140,255,.11)"], desert: ["#392a17", "rgba(255,213,140,.12)"] }[mapEl.value]; }
function snakeColor(i) { if (skinEl.value === "classic") return i ? "#5c8e36" : "#84b84b"; if (skinEl.value === "rainbow") return `hsl(${(i * 32 + score * 2) % 360} 83% 58%)`; return i ? "#1cbd79" : "#63f5ae"; }
function draw() { const [background, line] = mapStyle(); ctx.fillStyle = background; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = line; for (let i = 0; i <= grid; i++) { ctx.beginPath(); ctx.moveTo(i * box, 0); ctx.lineTo(i * box, canvas.height); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, i * box); ctx.lineTo(canvas.width, i * box); ctx.stroke(); }
  rocks.forEach(r => { ctx.fillStyle = mapEl.value === "desert" ? "#9a7851" : "#667c83"; drawRound(r.x * box + 3, r.y * box + 3, box - 6, box - 6, 4); }); const colors = { normal: "#ff7777", bonus: "#ffd166", slow: "#6cbcff", power: "#c18cff" }; ctx.fillStyle = colors[food.type]; ctx.beginPath(); ctx.arc(food.x * box + 10, food.y * box + 10, 7, 0, Math.PI * 2); ctx.fill(); if (food.type === "power") { ctx.fillStyle = "#fff"; ctx.fillRect(food.x * box + 9, food.y * box + 5, 2, 10); ctx.fillRect(food.x * box + 5, food.y * box + 9, 10, 2); }
  snake.forEach((part, i) => { ctx.fillStyle = snakeColor(i); drawRound(part.x * box + 1, part.y * box + 1, 18, 18, 7); if (!i) eyes(part); }); particles.forEach(p => { ctx.globalAlpha = p.life / 16; ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, 3, 3); }); ctx.globalAlpha = 1; }
function eyes(head) { const x = head.x * box, y = head.y * box, o = 5.5; ctx.fillStyle = "#092319"; ctx.beginPath(); if (direction === "LEFT" || direction === "RIGHT") { const ex = direction === "RIGHT" ? x + 14 : x + 6; ctx.arc(ex, y + o, 2, 0, Math.PI * 2); ctx.arc(ex, y + 14, 2, 0, Math.PI * 2); } else { const ey = direction === "DOWN" ? y + 14 : y + 6; ctx.arc(x + o, ey, 2, 0, Math.PI * 2); ctx.arc(x + 14, ey, 2, 0, Math.PI * 2); } ctx.fill(); }
function audio() { if (!audioContext) audioContext = new (window.AudioContext || window.webkitAudioContext)(); return audioContext; }
function sound(type) { if (!soundOn) return; try { const a = audio(), osc = a.createOscillator(), gain = a.createGain(); osc.frequency.value = type === "power" ? 810 : type === "bonus" ? 700 : 500; gain.gain.setValueAtTime(.04, a.currentTime); gain.gain.exponentialRampToValueAtTime(.001, a.currentTime + .13); osc.connect(gain).connect(a.destination); osc.start(); osc.stop(a.currentTime + .13); } catch (_) {} }
function toggleMusic() { musicOn = !musicOn; $("music-btn").textContent = `Music: ${musicOn ? "On" : "Off"}`; clearInterval(musicTimer); if (!musicOn) return; try { const notes = [220, 262, 330, 294], a = audio(); let n = 0; musicTimer = setInterval(() => { if (!musicOn) return; const o = a.createOscillator(), g = a.createGain(); o.frequency.value = notes[n++ % notes.length]; g.gain.setValueAtTime(.012, a.currentTime); g.gain.exponentialRampToValueAtTime(.001, a.currentTime + .2); o.connect(g).connect(a.destination); o.start(); o.stop(a.currentTime + .22); }, 360); } catch (_) {} }
function vibrate(ms) { if (vibrationEl.checked && navigator.vibrate) navigator.vibrate(ms); }
function endGame() { clearInterval(timer); started = false; $("pause-btn").disabled = true; stats.games++; stats.total += score; stats.longest = Math.max(stats.longest, snake.length); save("snakeArenaStats", stats); renderStats(); if (score) { leaderboard.push({ name: nameEl.value.trim() || "Player", score }); leaderboard.sort((a, b) => b.score - a.score); leaderboard = leaderboard.slice(0, 5); save("snakeArenaLeaderboard", leaderboard); renderLeaderboard(); } $("final-score").textContent = score; $("game-over-note").textContent = dailyMode ? (score >= 250 ? "Daily target achieved!" : "Try again to reach the daily target of 250.") : "Try another map or challenge mode."; $("game-over-modal").hidden = false; vibrate([70, 50, 100]); }
function togglePause() { if (!started || counting) return; paused = !paused; $("pause-btn").textContent = paused ? "Resume" : "Pause"; statusEl.textContent = paused ? "Game paused." : "Game resumed."; if (paused) clearInterval(timer); else configureTimer(); }
function share() { const text = `I scored ${score} in Snake Arena!`; if (navigator.share) navigator.share({ title: "Snake Arena", text }).catch(() => {}); else if (navigator.clipboard) navigator.clipboard.writeText(text).then(() => statusEl.textContent = "Score copied to clipboard."); }
document.addEventListener("keydown", e => { const keys = { ArrowLeft: "LEFT", ArrowRight: "RIGHT", ArrowUp: "UP", ArrowDown: "DOWN" }; if (keys[e.key]) { e.preventDefault(); setDirection(keys[e.key]); } if (e.key.toLowerCase() === "p") togglePause(); }); let touch;
canvas.addEventListener("touchstart", e => { const t = e.changedTouches[0]; touch = { x: t.clientX, y: t.clientY }; }, { passive: true }); canvas.addEventListener("touchend", e => { if (!touch) return; const t = e.changedTouches[0], dx = t.clientX - touch.x, dy = t.clientY - touch.y; touch = null; if (Math.max(Math.abs(dx), Math.abs(dy)) > 18) setDirection(Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? "RIGHT" : "LEFT") : (dy > 0 ? "DOWN" : "UP")); }, { passive: true });
document.querySelectorAll("[data-direction]").forEach(b => b.addEventListener("click", () => setDirection(b.dataset.direction))); $("start-btn").addEventListener("click", beginGame); $("restart-btn").addEventListener("click", beginGame); $("modal-restart-btn").addEventListener("click", beginGame); $("pause-btn").addEventListener("click", togglePause); $("sound-btn").addEventListener("click", () => { soundOn = !soundOn; $("sound-btn").textContent = `Sound: ${soundOn ? "On" : "Off"}`; }); $("music-btn").addEventListener("click", toggleMusic); $("share-btn").addEventListener("click", share); $("fullscreen-btn").addEventListener("click", () => document.documentElement.requestFullscreen?.()); $("theme-btn").addEventListener("click", () => { document.body.classList.toggle("light"); $("theme-btn").textContent = document.body.classList.contains("light") ? "Dark mode" : "Light mode"; });
bestEl.textContent = best; renderLeaderboard(); renderAchievements(); renderStats();
